### ISSUE TITLE
First inferences of diffusion model 

### ISSUE THREAD

**Issue by BreziTasbi** [ivadomed/Counterfactual_synthesis_for_lesion_segmentation#4]
The model takes a 3d volume as an input, noise it to the desired extend (from 0 to 1) and then perform diffusion from the point the input has been noised to, in order to generate a healthy spinal cord 3D volume.
This model have been trained on T2W spine generic samples.

- On a training T2w sample from spine generic
![3005_sct_gifs_2](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/5c893b09-9743-437b-8fe8-a3890154de1c)

- On a unseen T2w sample from canproco
![3005_canproco_gif_0](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/d9c87795-88b5-4d71-8bfe-c4989beb0700)

-On a injured patient T2W sample from sci-paris
![3005_sci_paris_gifs_9](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/0d6da793-20b2-4703-87e0-0a07de49f8d0)

-On a injured patient T2W sample from sci-paris with a very deformed spinal coord
![3005_sci_paris_gifs_2](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/1dc1f0e5-2faf-489f-bca2-0c67e1a5fa6d)

As we can see, the model looks fairly good at generating a credible counterfactual that folows the input even with high levels of noise (to 0.8). 
At the same time, low level of noise (from 0.2), are sufficient to make most of the lesions disappear.
Nevertheless, when we look at the actual difference map : there are actually differences everywhere, in particular on the edges.

Three ideas (that can be complementary) : 
- Run several inferences with different seeds and check is the mistakes don't get smooth out (easy and quick to do)
- Only focus on the spinal coord when comparing the input and the ouput thanks to sctr spinalcoord segmentation model (easy and quick to do)
- Implement a way to use a control net model in order to contrain the model into have the same edges / SC segmentation as the original input (long and hard to do)

**Comment by BreziTasbi** [comment]
After reading the control net paper : https://arxiv.org/abs/2302.05543 
it appears that a control net model is basically a duplication of the encoding part of the diffusion model with the decoding replaced by "zero convolutions layers". Thus The model is heavy to train and to use.


Then I came across this paper https://arxiv.org/abs/2302.08453
Which suggests a light weight alternative structure to perform the same task. Basically it trains a model to create vectors to add to the main model at some layer level in order to orient de diffusion toward the desired output (roughly the same way a text control would)
Since it is way lighter, requires less data and look easier to implement, I am willing to try to add it to the current model

**Comment by BreziTasbi** [comment]
I ran inference on sci-paris once more, only keeping differences on the spinal-cord segmentation and keeping only differences above a certain threshold in order to obtain some first segmentations. The results varies a lot depending on the input noise strength and the on the threshold. I decided to settle on a single setting for all the following images : 0.25 noising input and 0.3 threshold :

![lesion_segmentaiton_tr_0 3_gif_sci_paris_8_d=0 25_seg-manual](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/d8e0b3d2-421d-4103-8515-5ece796cb4b2)

![lesion_segmentaiton_tr_0 3_gif_sci_paris_1_d=0 25_seg-manual](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/34e583a2-f454-471a-836b-b48575b88f97)

![lesion_segmentaiton_tr_0 3_gif_sci_paris_10_d=0 25_seg-manual](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/516e75c5-d821-45cd-9be8-711ed2c63b5b)

![lesion_segmentaiton_tr_0 3_gif_sci_paris_11_d=0 25_seg-manual](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/e556e853-0ea7-464a-b590-ec070f966703)

![lesion_segmentaiton_tr_0 3_gif_sci_paris_0_d=0 25_seg-manual](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/3a1d1c57-9add-40ca-a56d-37a7d17df9fa)

![lesion_segmentaiton_tr_0 3_gif_sci_paris_8_d=0 25_seg-manual](https://github.com/ivadomed/Counterfactual_synthesis_for_lesion_segmentation/assets/164916503/e02af44a-7841-4d62-8239-8ee7c606a489)

Most of the time, the actual lesion seems to appear on the segmentation, yet a some undesired spots are segmented as well. sometimes a lot. The actual best setting of noising scale and threshold seems to vary a lot from a subject to another.
To be more specific, it looks like most undesired segmented area focus on the frontier of the spinal cord. Problem for which diffusion control tools can be really helpful.

**Comment by jcohenadad** [comment]
Very encouraging results!
